#!/bin/bash
#PBS -V
#PBS -N test3
#PBS -m ae
#PBS -M flejzerowicz@ucsd.edu
#PBS -o localhost:/Data/Programs/Xpbs/Xpbs/test/test3_${PBS_JOBID}.o
#PBS -e localhost:/Data/Programs/Xpbs/Xpbs/test/test3_${PBS_JOBID}.e
#PBS -l nodes=2:intel:ppn=12
#PBS -l mem=1gb
#PBS -l walltime=10:00:00


set -e
uname -a
echo "Conda environment is q2"
source activate q2
mkdir -p $TMPDIR/test3_${PBS_JOBNUM}
export TMPDIR=$TMPDIR/test3_${PBS_JOBNUM}
echo Temporary directory is $TMPDIR
echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
NPROCS=`wc -l < $PBS_NODEFILE`
NNODES=`uniq $PBS_NODEFILE | wc -l`
echo Using ${NPROCS} processors across ${NNODES} nodes
echo "/Data/Programs/Xpbs/Xpbs/test/test3_*.o"
echo "/Data/Programs/Xpbs/Xpbs/test/test3_*.e"
locdir=/localscratch/test3_${PBS_JOBNUM}/Data/Programs/Xpbs/Xpbs/test
rm -rf ${locdir}
mkdir -p ${locdir}
cd ${locdir}
echo Working directory is ${locdir}
echo "Job file:"
echo "/Data/Programs/Xpbs/Xpbs/test/test_loc_test.pbs"


mkdir -p ${locdir}/Data/Programs/Xpbs/Xpbs/test


cp ${locdir}/Data/Programs/Xpbs/Xpbs/test/to_print_for_test.txt ${locdir}/Data/Programs/Xpbs/Xpbs/test/to_print_for_test_copy.txt


rsync -auq ${locdir}/Data/Programs/Xpbs/Xpbs/test/ /Data/Programs/Xpbs/Xpbs/test
cd $PBS_O_WORKDIR
rm -rf ${locdir}

rm -fr $TMPDIR/${PBS_JOBNAME}_${PBS_JOBNUM}
echo "rm -fr $TMPDIR/${PBS_JOBNAME}_${PBS_JOBNUM}"
echo "Done!"
